Create database models
simplegoose/blog-app pull request #2
Opened 2023-08-18 20:40 UTC by simplegoose

In this PR the following was done:

- Models user, post, comment and like were created.
- Migrations to rename column posts_id were created to rename the column to post_id.

2023-08-18 22:48 UTC, Munsa1 requested changes
Hi @simplegoose , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Clean Codebase :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 22:48 UTC, Munsa1 commented on app/models/user.rb
> +  has_many :comments
- [ ] Kindly explicitly specify the foreign key for each association. This allows you to use custom column names for the foreign keys, 
Check the following example

```
has_many :posts, foreign_key: 'author_id'
has_many :comments, foreign_key: 'author_id'
has_many :likes, foreign_key: 'author_id'
```

2023-08-18 22:48 UTC, Munsa1 commented on app/models/post.rb
> +end
- [ ] Kindly create a private method that updates the post as per requirement.

e.g

```
private

  def update_post_counter
    author.increment!(:posts_counter)
  end
```

2023-08-18 22:48 UTC, Munsa1 commented on app/models/post.rb
> +end
- [ ] Kindly add a rails active call back `after_save` to call the `#update_post_counter` method every time a new post has been saved as per requirement. Also, do this for the `update_likes_count` method as well as the `update_comments_count` method in the like model and comment model respectively

2023-08-19 05:31 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @simplegoose, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  Implemented required changes. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 05:31 UTC, Qoosim commented on app/models/like.rb
> +  end
- [OPTIONAL] Great job implementing the required changes from the previous reviewer. Kindly make this method to be `private`. It is considered good practice to declare callback methods as private. If left public, they can be called from outside of the model and violate the principle of object encapsulation.

2023-08-19 05:31 UTC, Qoosim commented on app/models/comment.rb
> +  end
- [OPTIONAL] Great job implementing the required changes from the previous reviewer. Kindly make this method to be `private`. It is considered good practice to declare callback methods as private. If left public, they can be called from outside of the model and violate the principle of object encapsulation.

2023-08-19 08:08 UTC, merged