Controllers
simplegoose/blog-app pull request #4
Opened 2023-08-21 19:37 UTC by simplegoose

In this PR the following was done:

- A file users_controller.rb was created and route methods were added to the UsersController class.
- Routes were defined in the routes.rb file.
- Four view files were created to handle views for clients.

2023-08-21 20:10 UTC, aamirkhan2478 requested changes
Hi @simplegoose, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits polic to be empty for now.y](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-21 20:10 UTC, aamirkhan2478 commented on app/controllers/users_controller.rb
- [ ] Please add `posts_controller.rb` file because this is a requirement so kindly create `posts_controller.rb` inside this file you will add `index` and `show` method and for this milestone your method to be empty so kindly fix this issue as well :slightly_smiling_face:

2023-08-21 20:10 UTC, aamirkhan2478 commented on app/views/users/index.html.erb
- [ ] kindly add one folder called `posts` and inside the `posts` folder you can create the `index.html.erb` file and the `show.html.erb` file for now these files and folder are missing which are requirements so kindly fix this is as well :slightly_smiling_face:

2023-08-22 08:13 UTC, Ibizugbe approved these changes
Hi @simplegoose 👋🏼👋🏼👋🏼, 

![approved](https://github.com/simplegoose/blog-app/assets/64643995/14208a8a-4ffa-42db-aec2-1783db10c64f)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [ ] The `show` and `index` method has been added to the post_controller as required👍🏼.
- [x] Linters are passing👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 17:16 UTC, merged